about: Manage your project's issue templates
config:
  blank_issues_enabled: false
  contact_links:
    - name: OpenProphetDB Team
      url: https://www.prophetdb.org/contact/
      about: Please ask and answer questions here.
  issue_templates:
    - name: Bug report
      about: Create a report to help us improve
      labels: bug
      assignees: yjcyxky@163.com
    - name: Feature request
      about: Suggest an idea for this project
      labels: enhancement
      assignees: yjcyxky@163.com
