version: '3'

services:
  db:
    image: postgres: 15.3
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  neo4j:
    image: neo4j:4.3.6
    volumes:
      - ./neo4j-import:/var/lib/neo4j/import
      - ./neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_heap_maxSize: 512M
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms_default__listen__address: 