version: '3'

services:
  db:
    image: nordata/postgre_postgresml:14-27b1f33
    volumes:
      - ./data:/var/lib/postgresql/data
      - /tmp:/tmp
      # - /data:/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  neo4j:
    image: neo4j:5.14.0-community
    volumes:
      - ./neo4j-import:/var/lib/neo4j/import
      - ./neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      # For more details, see https://neo4j.com/docs/operations-manual/current/docker/ref-settings/
      NEO4J_AUTH: neo4j/password
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 2G
      NEO4J_server_default__listen__address: 