version: '3'

services:
  postgres-ml:
    image: nordata/postgresml:2.7.13
    # image: nordata/postgre_postgresml:14-27b1f33
    container_name: biomedgps-postgresql-ml
    restart: "on-failure"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # If you got the following error: The cluster is owned by user id 105 which does not exist, Please run: chown -R 101:103 ./data
      # If you got error message: /var/lib/postgresql/15/main is not accessible or does not exist, please delete the data folder and recreate it
      - pg_ml_data:/var/lib/postgresql
      - ./conf/entrypoint.sh:/app/entrypoint.sh
      - ./conf/dashboard.sh:/app/dashboard.sh
      # For importing data, you must keep the data in the following folder
      - /tmp:/tmp
      # For Macos, you must keep the data in the following folder
      - /var/folders:/var/folders
      - ./conf/postgresql.conf:/etc/postgresql/15/main/postgresql.conf
    ports:
      - 127.0.0.1:5433:5432
      - 127.0.0.1:8888:8000
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 100

  neo4j:
    image: neo4j:5.14.0-community
    container_name: biomedgps-neo4j
    restart: "on-failure"
    volumes:
      - ./neo4j-import:/var/lib/neo4j/import
      - ./neo4j-data:/data
      - ./plugins:/var/lib/neo4j/plugins
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      # For more details, see https://neo4j.com/docs/operations-manual/current/docker/ref-settings/
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 2G
      NEO4J_server_default__listen__address: 
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_memory_transaction_total_max: 10G

volumes:
  pg_ml_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
